// Voiceprint voice scorer: TypeScript port of the portable surface features and the logistic model.
// Dependency-free. Generated by `voiceprint`, which injects LEXICONS and VOICE_SCORER below from the
// Python run, so the word lists and weights can never drift from the model that was evaluated.
// Parity with the Python implementation is tested (tests/test_ts_parity.py).
//
//   import { scoreVoice } from './voiceScorer';
//   scoreVoice('hey Sam! yes that works 🙂')  // → 0..1, how on-voice the message is

/** The scorer section of a Voiceprint voice.json. */
export interface VoiceprintModel {
  type: string;
  features: readonly string[];
  log1p: readonly string[];
  mean: readonly number[];
  scale: readonly number[];
  coef: readonly number[];
  intercept: number;
  cv_auc?: number | null;
}

/* __LEXICONS__ */
/* __MODEL__ */

const WORD = /[A-Za-z][A-Za-z'’-]*|\d+(?:[.,]\d+)?/g;
const SENT_SPLIT = /(?<=[.!?…])\s+(?=[A-Z0-9"“'(<])|\n+/;
const EMOTICON = /(?:[:;=8xX][-o^']?[)(\]\[dDpP/\\|*@3]|<3|\^_\^|:'\(|¯\\_\(ツ\)_\/¯)/g;
const PLACEHOLDER = /<[A-Z_]+(?:_\d+)?>/g;
const URLISH = /https?:\/\/\S+|www\.\S+/g;
// One emoji: a pictographic base with optional variation selector, skin tone and ZWJ continuations;
// regional-indicator pairs (flags); keycaps.
const EMOJI = /(?:\p{Regional_Indicator}{2}|[#*0-9]️?⃣|\p{Extended_Pictographic}(?:️|\p{Emoji_Modifier})?(?:‍\p{Extended_Pictographic}(?:️|\p{Emoji_Modifier})?)*)/gu;

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const phraseRe = (items: readonly string[]) =>
  new RegExp('\\b(?:' + [...items].sort((a, b) => b.length - a.length).map(escapeRe).join('|') + ')\\b', 'gi');

const HEDGE_RE = phraseRe(LEXICONS.hedges);
const BOOST_RE = phraseRe(LEXICONS.boosters);
const INTENS_RE = phraseRe(LEXICONS.intensifiers);
const DM_RE = phraseRe(LEXICONS.discourse_markers);
const EXPAND_RE = phraseRe(LEXICONS.expandable);
const TEXTESE_RE = phraseRe(LEXICONS.textese);
const CONTRACTION = new RegExp(LEXICONS.contractions_re, 'gi');
const PRON: Record<string, Set<string>> = Object.fromEntries(
  Object.entries(LEXICONS.pronouns).map(([k, v]) => [k, new Set<string>(v as readonly string[])]),
);

const count = (re: RegExp, s: string) => (s.match(re) ?? []).length;
const cps = (s: string) => Array.from(s); // code points, matching Python string indexing
const isUpperWord = (w: string) => w === w.toUpperCase() && w !== w.toLowerCase();
const isAlpha = (c: string) => /\p{L}/u.test(c);
const isLower = (c: string) => c !== c.toUpperCase() && c === c.toLowerCase();
const isUpper = (c: string) => c !== c.toLowerCase() && c === c.toUpperCase();
const pyStrip = (s: string) => s.replace(/^\s+|\s+$/g, '');

export function sentences(text: string): string[] {
  return text.split(SENT_SPLIT).map((s) => (s ?? '').trim()).filter(Boolean);
}

export function words(text: string): string[] {
  return text.replace(URLISH, ' URL ').replace(PLACEHOLDER, ' NAME ').match(WORD) ?? [];
}

function emojiInfo(text: string): [number, string] {
  const found = [...text.matchAll(EMOJI)];
  if (!found.length) return [0, 'none'];
  const stripped = pyStrip(text);
  if (pyStrip(stripped.replace(EMOJI, '')) === '') return [found.length, 'standalone'];
  // positions in code points, as in Python
  const cpIndex = (i: number) => cps(text.slice(0, i)).length;
  const first = cpIndex(found[0].index!);
  const lastM = found[found.length - 1];
  const last = cpIndex(lastM.index! + lastM[0].length);
  const lead = cps(text).length - cps(text.replace(/^\s+/, '')).length;
  if (first <= lead + 1) return [found.length, 'lead'];
  const tail = cps(text).slice(last).join('');
  if (last >= cps(stripped).length - 1 || !tail.replace(/^[ .!?]+|[ .!?]+$/g, '')) return [found.length, 'end'];
  return [found.length, 'inline'];
}

function onlyNamesCapitalised(text: string): boolean {
  const caps = text.match(/\b[A-Z][a-z']*/g) ?? [];
  return caps.length <= 1 && !/^[^\p{L}\p{N}_]*[A-Z][a-z']*\s+[a-z]/u.test(text);
}

function stripTail(text: string): string {
  const t = text.replace(EMOJI, '').replace(/\s+$/, '');
  const tail = cps(t).slice(-4).join('');
  return new RegExp(EMOTICON.source).test(tail) ? tail.replace(EMOTICON, '').replace(/\s+$/, '') : t;
}

export function casing(raw: string): string {
  const text = raw.replace(PLACEHOLDER, ' ');
  const letters = cps(text).filter(isAlpha);
  if (!letters.length) return 'none';
  if (letters.every(isLower)) return 'all_lower';
  if (letters.filter(isUpper).length / letters.length > 0.7 && letters.length > 6) return 'shouting';
  const starts: string[] = [];
  for (const s of sentences(text)) {
    const m = /^[^\p{L}\p{N}_]*([A-Za-z][\p{L}\p{N}_']*)([!,])?\s*([\p{L}\p{N}_])?/u.exec(s);
    if (!m) continue;
    const [, word, punct, nxt] = m;
    starts.push(punct && isUpper(word[0]) && nxt ? nxt : word[0]);
  }
  if (starts.length && starts.filter(isAlpha).every(isLower)) {
    return onlyNamesCapitalised(text) ? 'all_lower' : 'lower_starts';
  }
  return 'standard';
}

export function features(text: string): Record<string, number> {
  const ws = words(text);
  const nw = Math.max(ws.length, 1);
  const lw = ws.map((w) => w.toLowerCase());
  const sents = sentences(text).length ? sentences(text) : [text];
  const ns = sents.length;
  const [nEmoji, epos] = emojiInfo(text);
  const tail = stripTail(text);
  const cas = casing(text);
  const occurrences = (sub: string) => text.split(sub).length - 1;
  const f: Record<string, number> = {
    words: ws.length,
    words_per_sentence: ws.length / ns,
    mean_word_length: ws.reduce((a, w) => a + w.length, 0) / nw,
    long_word_rate: ws.filter((w) => w.length >= 7).length / nw,
    line_breaks: occurrences('\n'),
    is_fragment: Number(ws.length <= 3 && !/[.!?]$/.test(pyStrip(text))),
    exclamations_per_sentence: occurrences('!') / ns,
    questions_per_sentence: occurrences('?') / ns,
    ends_with_question: Number(tail.endsWith('?')),
    ends_with_exclamation: Number(tail.endsWith('!')),
    ends_without_punctuation: Number(tail.length > 0 && /[\p{L}\p{N}]/u.test(cps(tail).slice(-1)[0])),
    ellipses_per_sentence: (occurrences('...') + occurrences('…')) / ns,
    multi_exclamation: Number(/!{2,}/.test(text)),
    commas_per_sentence: occurrences(',') / ns,
    dashes_per_sentence: (occurrences(' - ') + occurrences('—') + occurrences('–')) / ns,
    has_emoji: Number(nEmoji > 0),
    emoji_end: Number(epos === 'end'),
    emoji_lead: Number(epos === 'lead'),
    emoticons: count(EMOTICON, text),
    all_lowercase: Number(cas === 'all_lower'),
    lowercase_sentence_starts: Number(cas === 'lower_starts'),
    capitalised_words_rate: ws.filter((w) => isUpperWord(w) && w.length > 1).length / nw,
    contraction_rate: count(CONTRACTION, text) / nw,
    uncontracted_forms: count(EXPAND_RE, text) / nw,
    hedge_rate: count(HEDGE_RE, text) / nw,
    booster_rate: count(BOOST_RE, text) / nw,
    intensifier_rate: count(INTENS_RE, text) / nw,
    discourse_marker_rate: count(DM_RE, text) / nw,
    textese_rate: count(TEXTESE_RE, text) / nw,
    addresses_by_name_first: Number(/^[^\p{L}\p{N}_]*(hi|hey|hello|dear|thanks|thank you)?[^\p{L}\p{N}_]*<PERSON_\d+>/iu.test(text)),
  };
  for (const [k, v] of Object.entries(PRON)) f[`pronoun_${k}`] = lw.filter((w) => v.has(w)).length / nw;
  return f;
}

/** Probability (0..1) that `text` is in the extracted voice. */
export function scoreVoice(text: string, model: VoiceprintModel | null = VOICE_SCORER): number {
  if (!model) throw new Error('voiceScorer: no model. Pass the `scorer` object from a Voiceprint voice.json.');
  const f = features(text);
  let z = model.intercept;
  model.features.forEach((name, j) => {
    let x = f[name] ?? 0;
    if (model.log1p.includes(name)) x = Math.log1p(x);
    z += ((x - model.mean[j]) / model.scale[j]) * model.coef[j];
  });
  return 1 / (1 + Math.exp(-z));
}
